name: Build

on:
  push:
  schedule:
    - cron: "0 0 * * Sun"

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Build Image
        run: |
          min_tag=0.26.0
          docker buildx create --use --driver=docker-container
          pip3 install semver
          readonly latest="$(curl -sSL https://api.github.com/repos/aws-observability/aws-otel-collector/releases/latest | jq -r ".tag_name")"
          readonly tags="$(curl -sSL https://api.github.com/repos/aws-observability/aws-otel-collector/releases | jq -r ".[].tag_name" | grep '^v' | tac)"
          for tag in ${tags}; do
            if python -c "import semver; exit(semver.compare('${tag/v/}', '${min_tag}') >= 0)"; then
              continue
            fi

            echo "::group::${tag}"
            args=(--tag ghcr.io/${{ github.repository }}:${tag})
            if [[ ${tag} == ${latest} ]]; then
              args+=(--tag ghcr.io/${{ github.repository }}:latest)
            fi
            docker buildx build . \
              --build-arg BASE_TAG=${tag} \
              --push \
              --cache-to type=gha,mode=max \
              --cache-from type=gha \
              ${args[@]} \
            || echo "Error: ${tag}"
            echo "::endgroup::"
          done
